fos_user:
    db_driver: orm
    user_class: Paroki\User\Entity\User
    firewall_name: main
    from_email:
        address: "me@itstoni.com"
        sender_name: "Anthonius Munthi"

framework:
    translator: ~
    templating:
        engines: twig

api_platform:
    path_segment_name_generator: 'siap.core.api.operation_path_resolver'
    enable_fos_user: true

doctrine:
    dbal:
        types:
            uuid:  Ramsey\Uuid\Doctrine\UuidType
