dist: xenial
language: php

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm
    - $TRAVIS_BUILD_DIR/client/node_modules

node_js:
  - "10"

stages:
  - test
  - deploy
  
jobs:
  include:
    - stage: test
      php: '7.3'  
    - stage: test
      php: '7.3'
    - stage: test
      php: '7.3'
      env: COVERAGE=yes
    - stage: deploy
      php: '7.2'
      env: 'BUILD=yes INTEGRATION=yes'
      deploy:
        provider: script
        script: etc/travis/deploy.sh
        skip_cleanup: true
        on:
          branch: master
  allow_failures:
    - env: COVERAGE=yes

before_install:
  # remove xdebug when not collecting code coverage
  - if [[ $COVERAGE != yes ]]; then phpenv config-rm xdebug.ini || echo "xdebug not available"; fi;

install:
  - cp etc/travis/env.local api/.env.local
  - cd $TRAVIS_BUILD_DIR/api
  - composer install --ansi
  - composer prepare-test --ansi
  - cd $TRAVIS_BUILD_DIR/client
  - yarn install
  - if [[ $BUILD == yes ]]; then yarn build; fi;

script:
- cd $TRAVIS_BUILD_DIR
- ./etc/travis/test.sh
- cd client
- yarn test:unit

before_deploy:
- cd $TRAVIS_BUILD_DIR
- openssl aes-256-cbc -K $encrypted_6041831ee8a2_key -iv $encrypted_6041831ee8a2_iv -in etc/travis/deploy_key.enc -out deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host $IP\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
- rsync -r $TRAVIS_BUILD_DIR/client/dist travis@$IP:$DEPLOY_DIR

after_script:
  # process coverage
  - 'if [[ $COVERAGE = yes ]]; then
        cd $TRAVIS_BUILD_DIR;
        wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar;
        chmod +x php-coveralls.phar;
        travis_retry ./php-coveralls.phar --json_path=api/build/logs/coveralls-upload.json -vvv -x $TRAVIS_BUILD_DIR/api/build/logs/clover.xml;
        wget https://scrutinizer-ci.com/ocular.phar;
        travis_retry php ocular.phar code-coverage:upload --format=php-clover api/build/logs/clover.xml;
    fi'
