dist: xenial

sudo: required

language: php

notifications:
  email:
    on_failure: change
    on_success: never

cache:
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.npm"
    - "$TRAVIS_BUILD_DIR/client/node_modules"

stages:
  - test
  - deploy

jobs:
  include:
    - stage: test
      php: '7.2'
      env: API=yes
    - stage: test
      php: '7.3'
      env: API=yes
    - stage: test
      php: '7.3'
      env: CLIENT=yes
    - stage: test
      php: '7.3'
      env: COVERAGE=yes
    - stage: test
      php: '7.2'
      env: INTEGRATION=yes
      addons:
        apt:
          packages:
            - nginx
        hosts:
          - siap.localhost
    - stage: deploy
      if: branch in (master,travis-debug) AND type != pull_request
      php: '7.2'
      env: DEPLOY=yes
      deploy:
        provider: script
        script: etc/travis/deploy.sh
        skip_cleanup: true
        on:
          branch: master
  allow_failures:
    - env: COVERAGE=yes
    - env: INTEGRATION=yes
    - env: DEPLOY=yes
  fast_finish: true

before_install:
  - if [[ $COVERAGE != yes ]]; then phpenv config-rm xdebug.ini || echo "xdebug not available"; fi;
  - sudo service postgresql stop
  # wait for postgresql to shutdown
  - while sudo lsof -Pi :5432 -sTCP:LISTEN -t; do sleep 1; done

install:
  - etc/travis/install.sh

script:
  - cd $TRAVIS_BUILD_DIR
  - if [[ $INTEGRATION != yes && $DEPLOY != yes ]]; then ./etc/travis/test.sh; fi;
  - if [[ $INTEGRATION = yes ]]; then ./etc/travis/integration.sh; fi;

before_deploy:
  - cd $TRAVIS_BUILD_DIR
  - openssl aes-256-cbc -K $encrypted_6041831ee8a2_key -iv $encrypted_6041831ee8a2_iv
    -in etc/travis/deploy_key.enc -out deploy_key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ./deploy_key
  - echo -e "Host $IP\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - ssh-add ./deploy_key
  - rsync --stats --progress -avh --delete-before $TRAVIS_BUILD_DIR/client/dist travis@$IP:$DEPLOY_DIR

after_script:
  - etc/travis/after-script.sh
