language: php

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

stages:
  - test
  - deploy
  
jobs:
  include:
    - stage: test
      php: '7.2'
    - stage: test
      php: '7.3'
    - stage: test
      php: '7.3'
      env: COVERAGE=yes
    - stage: deploy
      php: '7.2'
      install: "echo 'No install required'"
      script: "echo 'No script during deploy'"
      deploy:
        provider: script
        script: etc/travis/deploy.sh
        skip_cleanup: true
        on:
          branch: travis-build
  allow_failures:
    - env: COVERAGE=yes

before_install:
  # remove xdebug when not collecting code coverage
  - if [[ $COVERAGE != yes ]]; then phpenv config-rm xdebug.ini || echo "xdebug not available"; fi;
install:
  - cp etc/travis/env.local .env.local
  - yarn install
  - composer install --ansi

script:
- ./bin/phpunit

before_deploy:
- openssl aes-256-cbc -K $encrypted_6041831ee8a2_key -iv $encrypted_6041831ee8a2_iv
  -in etc/travis/deploy_key.enc -out deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host $IP\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
- chmod +x etc/travis/deploy.sh
