version: "3"
services:
    nginx:
        image: nginx:alpine
        container_name: ${DOCKER_CONTAINER_NAME}.nginx
        volumes:
            - ./etc/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www/siap:rw
        ports:
            - "80:80"
        links:
            - php
            - db
        environment:
            - UMASK="0000"

    php:
        container_name: ${DOCKER_CONTAINER_NAME}.php
        build:
            context: etc/docker/php
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ./:/var/www/siap:rw,cached
            - ./var:/var/www/siap/var:rw
        links:
            - db

    db:
        container_name: ${DOCKER_CONTAINER_NAME}.db
        # In production, you may want to use a managed database service
        image: postgres:10-alpine
        environment:
            - POSTGRES_DB=paroki
            - POSTGRES_USER=paroki
            # You should definitely change the password in production
            - POSTGRES_PASSWORD=paroki
        volumes:
            # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
            - ./var/db/data:/var/lib/postgresql/data:rw
        ports:
            - "5432:5432"

    #client:
    #    container_name: ${DOCKER_CONTAINER_NAME}.client
    #    build:
    #        context: ./etc/docker/client
    #    volumes:
    #        - ./:/usr/src/client:rw,cached
    #        - /usr/src/client/node_modules
    #    ports:
    #        - "8080:8080"
