framework:
    templating:
        engines: twig
    default_locale: 'id'
    translator:
        fallbacks: ['id']

api_platform:
    path_segment_name_generator: 'siap.core.api.operation_path_resolver'
    collection:
        pagination:
            items_per_page: 5
    enable_nelmio_api_doc: true
    
nelmio_api_doc:
    documentation:
        info:
            title: SIAP
            description: Sistim Informasi dan Administrasi Paroki
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/(?!/doc$) # Accepts routes under /api except /api/doc

