framework:
    templating:
        engines: twig
    default_locale: 'id'
    translator:
        fallbacks: ['id']

api_platform:
    path_segment_name_generator: 'siap.core.api.operation_path_resolver'
    collection:
        pagination:
            items_per_page: 5

doctrine:
    dbal:
        types:
            uuid:  Ramsey\Uuid\Doctrine\UuidType

