SIAP\Reference\Entity\Paroki:
    attributes:
        route_prefix: '/reference'
    collectionOperations:
        get: ~
        post: ~
    itemOperations:
        get:
            path: '/paroki/{id}.{_format}'
            requirements:
                id: '\d{3}\.\d{3}'
        put: ~
        delete: ~
