SIAP\User\Entity\User:
    enable_max_depth: true
    attributes:
        id:
            groups: ['read']
        nama:
            groups: ['read', 'write']
        foto:
            groups: ['read', 'foto']
            max_depth: 1
        username:
            groups: ['read','write']
        email:
            groups: ['read','write']
        enabled:
            groups: ['read','write']
        groups:
            groups: ['read','write']
        roles:
            groups: ['read','write']
        plainPassword:
            groups: ['write']
        paroki:
            groups: ['read', 'paroki']
