SIAP\Core\Entity\MediaObject:
    attributes:
        id:
            groups: ['read']
        uploadedAt:
            groups: ['read', 'write']
        filePath:
            groups: ['read', 'write']
        contentUrl:
            groups: ['read', 'write']
