api_platform:
    resource: .
    type: api_platform
    prefix: /


login_check:
    path: /login-check
    methods: [POST]

bundle_routes:
    resource: '@ReferenceBundle/Controller/'
    type: annotation

core_controllers:
    resource: ../../Controller/
    type: annotation
