SIAP\Core\Entity\MediaObject:
    shortname: media
    iri: "http://schema.org/MediaObject"
    attributes:
        normalizationContext:
            groups: ['media_object_read']
        get: ~
    itemOperations:
        get: ~
