SIAP\User\Entity\User:
    attributes:
        normalization_context:
            groups: ['read']
        denormalization_context:
            groups: ['write']
    collectionOperations:
        get:
            filters:
                - siap.user.orders.user
            groups: ['read']
        post: ~
    itemOperations:
        get: ~
        put: ~
        delete: ~
        profile_get:
            method: GET
            path: /profile/{id}
            access_control: 'is_granted("ROLE_USER") and object == user'
            access_control_message: 'Hanya user yang bersangkutan bisa mengubah profil'
        profile_update:
            method: PUT
            path: /profile/{id}
            access_control: 'is_granted("ROLE_USER") and object == user'
            access_control_message: 'Hanya user yang bersangkutan bisa mengubah profil'
        profile_password:
            method: PUT
            path: /profile-password/{id}
            access_control: 'is_granted("ROLE_USER") and object == user'
            access_control_message: 'Hanya user yang bersangkutan bisa mengubah password'
            validation_groups: ['password', 'profile-password']
            
        upload_foto:
            method: POST
            path: /user/{id}/upload-foto
            controller: siap.core.controller.media_upload
            defaults:
                property: foto
            swagger_context:
                summary: Upload user foto
                consumes: [ 'multipart/form-data' ]
                parameters:
                    - 
                        in: formData
                        name: 'picture'
                        type: 'file'
                        description: 'The file to upload'
    properties:
        paroki: ~
        foto:
            groups: ['read']
