SIAP\Core\Entity\MediaObject:
    file:
        uri_prefix: /images
        mapping: media_object
        filename_property: fileName
        size: size
        mime_type: mimeType
        original_name: originalName
        dimensions: dimensions
        
        upload_destination: '%kernel.project_dir%/public/images/avatars'
        inject_on_load: true
        delete_on_update: true
        delete_on_remove: true
