SIAP\User\Entity\User:
    attributes:
        normalization_context:
            groups: ['read','paroki']
        denormalization_context:
            groups: ['write']
    collectionOperations:
        get:
            filters:
                - siap.user.orders.user
            groups: ['read']
        post: ~
    itemOperations:
        get: ~
        put: ~
        delete: ~
    properties:
        paroki:
