api_platform:
    resource: .
    type: api_platform
    prefix: /api


login_check:
    path: /login_check
    methods: [POST]

core_controllers:
    resource: ../../Controller/
    type: annotation
