api_platform:
    resource: .
    type: api_platform
    prefix: /api


login_check:
    path: /api/login_check
    methods: [POST]

bundle_routes:
    resource: '@ReferenceBundle/Controller/'
    type: annotation

core_controllers:
    resource: ../../Controller/
    type: annotation
