SIAP\Reference\Entity\Paroki:
    attributes:
        route_prefix: '/reference'
    collectionOperations:
        get:
            filters:
                - siap.reference.filters.paroki
        search:
            route_name: siap_search_paroki
        post: ~
    itemOperations:
        get: ~
        put: ~
        delete: ~
    properties: ~
